server:
  # 应用端口
  port: 7081
  # tomcat 配置
  tomcat:
    max-threads: 500 # 最大线程数量 默认200
    uri-encoding: UTF-8
    max-connections: 1000 # 最大连接数量 1000
    min-spare-threads: 50 # 初始化线程是20
    basedir: /home/www/tmp
  connection-timeout: 20000
  context-path: /pay

# javamelody
javamelody:
  init-parameters:
    storage-directory: api

# 激活配置文件
spring:
  profiles:
    active: dev
